# Site
repository: fadytadrous/My-CV
# favicon: images/favicon.ico

# Personal info
name: Fady Tadrous
title: Biomedical-Engineer
email: fadytadrous.ft@gmail.com
website: www.github.com/fadytadrous

# Social links
#twitter_username:
github_username:  fadytadrous
# dribbble_username: jekyll
facebook_username: fady.tadrous
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fady and I'm a student in faculty of engineering Cairo university.
  I'm most skilled in: <mark>Time management</mark> and <mark>Teamwork</mark>

# Projects Section
# projects_title: Projects
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Cycling
   - Gaming
   - Playing piano
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

url: fadytadrous.github.io
baseurl: /My-CV
exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
